package gg.askai.android.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

/**
 * Tiny i18n layer. English is the default; Bosnian translates the whole app.
 * `tr(lang,key)` works anywhere (plain code), `t(key)` inside composables via
 * LocalLang. AI replies are translated by the engine (AgentRunner.language).
 */
val LocalLang = compositionLocalOf { "en" }

@Composable
fun t(key: String): String = tr(LocalLang.current, key)

fun tr(lang: String, key: String): String =
    (if (lang == "bs") BS[key] else null) ?: EN[key] ?: key

private val EN = mapOf(
    "new_chat" to "New chat",
    "search_chats" to "Search chats",
    "recent" to "Recent",
    "workspace" to "Workspace",
    "settings" to "Settings",
    "sign_out" to "Sign out",
    "voice_call" to "Voice call",
    "agents" to "Agents",
    "channels" to "Channels",
    "jobs" to "Jobs",
    "knowledge" to "Knowledge",
    "apps" to "Apps",
    "greeting" to "Your move, %s!",
    "ask" to "Ask AskAI",
    "thinking" to "Thinking…",
    "regenerate" to "Regenerate",
    "update_available" to "Update available — v%s",
    "you_have" to "You have v%s. Tap to install.",
    "later" to "Later",
    "update" to "Update",
    "downloading" to "Downloading %s%%…",
    "account" to "Account",
    "model" to "Model",
    "appearance" to "Appearance",
    "light" to "☀️ Light",
    "dark" to "🌙 Dark",
    "auto" to "📱 Auto",
    "language" to "Language",
    "custom_instructions" to "Custom instructions",
    "instructions_hint" to "How should Parable 6 respond? (tone, style, what you're working on…)",
    "save" to "Save",
    "app_section" to "App",
    "check_updates" to "Check for updates",
    "install_update" to "Install update v%s",
    "newer_ready" to "A newer version is ready to install",
    "checking" to "Checking…",
    "on_latest" to "You're on the latest — v%s",
    "current_ver" to "Current version v%s",
    "parable_sub" to "Flagship — deepest reasoning & research",
    "turbo_sub" to "Faster answers for everyday tasks",
    "parable_menu_sub" to "Deepest reasoning",
    "turbo_menu_sub" to "Fast everyday answers",
    "ready" to "Ready",
    "connecting" to "Connecting…",
    "listening" to "Listening…",
    "speaking" to "Speaking…",
    "start_call" to "Start call",
    "end_call" to "End call",
    "tap_to_start" to "Tap to start a live conversation",
    "tap_again" to "Tap to talk again",
    "nothing_yet" to "Nothing here yet",
    "no_agents" to "No agents yet",
    "agents_line" to "Your team's AI agents will appear here.",
    "no_apps" to "No apps yet",
    "apps_line" to "Ask Parable 6 to build a website or app.",
    "channels_line" to "Team channels will appear here.",
    "jobs_line" to "Background jobs and tasks will appear here.",
    "knowledge_line" to "Your knowledge base documents will appear here.",
    "tap_open" to "Tap to open",
    "email" to "Email",
    "password" to "Password",
    "sign_in" to "Sign in",
    "create_account" to "Create account",
    "have_account" to "Have an account? Sign in",
    "new_here" to "New here? Create an account",
    "auth_err_login" to "Wrong email or password.",
    "auth_err_signup" to "Couldn't create the account.",
)

private val BS = mapOf(
    "new_chat" to "Novi razgovor",
    "search_chats" to "Pretraži razgovore",
    "recent" to "Nedavno",
    "workspace" to "Radni prostor",
    "settings" to "Postavke",
    "sign_out" to "Odjava",
    "voice_call" to "Glasovni poziv",
    "agents" to "Agenti",
    "channels" to "Kanali",
    "jobs" to "Poslovi",
    "knowledge" to "Znanje",
    "apps" to "Aplikacije",
    "greeting" to "Tvoj potez, %s!",
    "ask" to "Pitaj AskAI",
    "thinking" to "Razmišljam…",
    "regenerate" to "Ponovo generiši",
    "update_available" to "Dostupno ažuriranje — v%s",
    "you_have" to "Imaš v%s. Dodirni za instalaciju.",
    "later" to "Kasnije",
    "update" to "Ažuriraj",
    "downloading" to "Preuzimanje %s%%…",
    "account" to "Račun",
    "model" to "Model",
    "appearance" to "Izgled",
    "light" to "☀️ Svijetla",
    "dark" to "🌙 Tamna",
    "auto" to "📱 Auto",
    "language" to "Jezik",
    "custom_instructions" to "Prilagođene upute",
    "instructions_hint" to "Kako Parable 6 treba odgovarati? (ton, stil, na čemu radiš…)",
    "save" to "Sačuvaj",
    "app_section" to "Aplikacija",
    "check_updates" to "Provjeri ažuriranja",
    "install_update" to "Instaliraj ažuriranje v%s",
    "newer_ready" to "Novija verzija je spremna za instalaciju",
    "checking" to "Provjeravam…",
    "on_latest" to "Imaš najnoviju verziju — v%s",
    "current_ver" to "Trenutna verzija v%s",
    "parable_sub" to "Vodeći model — najdublje razmišljanje i istraživanje",
    "turbo_sub" to "Brži odgovori za svakodnevne zadatke",
    "parable_menu_sub" to "Najdublje razmišljanje",
    "turbo_menu_sub" to "Brzi svakodnevni odgovori",
    "ready" to "Spremno",
    "connecting" to "Povezivanje…",
    "listening" to "Slušam…",
    "speaking" to "Govorim…",
    "start_call" to "Započni poziv",
    "end_call" to "Završi poziv",
    "tap_to_start" to "Dodirni za razgovor uživo",
    "tap_again" to "Dodirni da nastaviš razgovor",
    "nothing_yet" to "Još ništa ovdje",
    "no_agents" to "Još nema agenata",
    "agents_line" to "Ovdje će se pojaviti AI agenti tvog tima.",
    "no_apps" to "Još nema aplikacija",
    "apps_line" to "Zamoli Parable 6 da napravi web stranicu ili aplikaciju.",
    "channels_line" to "Ovdje će se pojaviti kanali tima.",
    "jobs_line" to "Ovdje će se pojaviti pozadinski poslovi i zadaci.",
    "knowledge_line" to "Ovdje će se pojaviti dokumenti baze znanja.",
    "tap_open" to "Dodirni da otvoriš",
    "email" to "Email",
    "password" to "Lozinka",
    "sign_in" to "Prijavi se",
    "create_account" to "Kreiraj račun",
    "have_account" to "Imaš račun? Prijavi se",
    "new_here" to "Novi si ovdje? Kreiraj račun",
    "auth_err_login" to "Pogrešan email ili lozinka.",
    "auth_err_signup" to "Nije moguće kreirati račun.",
)
